GET http://localhost:8080/api/user_data
Authorization: Bearer
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImVtYWlsIjoidGVzdDNAeWFob28uY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkQ3ZBbGFUQjRIUEQ1NHBNUDcwVE5pdWRGWlZBQUZHWEFyNlQyTU0zYWtXYjIxWWphdVlBWkcifSwiaWF0IjoxNjExMjk5OTcwLCJleHAiOjE2MTEzMDM1NzAsInN1YiI6IjUifQ.ArX_zkvPjiGu_Z2S2byUVUir4gAXkdTe8i7DHPh_CGc

### 

POST http://localhost:8080/api/login
content-type: application/json

{
    "email": "test3@yahoo.com",
    "password": "test"
}